import { StyleSheet } from 'react-native';
import { SHARED_STYLE_COLORS } from '@/lib/constants/sharedStyles';

export const sourceVideoStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: SHARED_STYLE_COLORS.background,
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    paddingHorizontal: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: SHARED_STYLE_COLORS.backgroundTertiary,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: SHARED_STYLE_COLORS.text,
  },
  limitText: {
    fontSize: 14,
    color: SHARED_STYLE_COLORS.textMuted,
    marginTop: 4,
  },
  content: {
    flex: 1,
    padding: 20,
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  planInfoContainer: {
    backgroundColor: SHARED_STYLE_COLORS.backgroundSecondary,
    padding: 12,
    borderRadius: 8,
    marginBottom: 16,
    alignItems: 'center',
  },
  planInfoText: {
    color: SHARED_STYLE_COLORS.textMuted,
    fontSize: 14,
  },
  errorContainer: {
    backgroundColor: SHARED_STYLE_COLORS.primaryOverlay,
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
  },
  errorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  errorTitle: {
    color: SHARED_STYLE_COLORS.error,
    fontSize: 16,
    fontWeight: '600',
  },
  errorText: {
    color: SHARED_STYLE_COLORS.error,
    fontSize: 14,
    marginBottom: 12,
  },
  errorActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  errorButton: {
    backgroundColor: SHARED_STYLE_COLORS.error,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  supportButton: {
    backgroundColor: SHARED_STYLE_COLORS.backgroundSecondary,
    borderWidth: 1,
    borderColor: SHARED_STYLE_COLORS.error,
  },
  errorButtonText: {
    color: SHARED_STYLE_COLORS.text,
    fontSize: 14,
    fontWeight: '500',
  },
  limitContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: SHARED_STYLE_COLORS.primaryOverlay,
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    gap: 12,
  },
  limitTextContainer: {
    flex: 1,
  },
  limitTitle: {
    color: SHARED_STYLE_COLORS.accent,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 4,
  },
  limitDescription: {
    color: SHARED_STYLE_COLORS.warning,
    fontSize: 14,
    lineHeight: 20,
  },
  uploadSection: {
    gap: 20,
  },
  uploadDisabled: {
    width: '100%',
    height: 120,
    backgroundColor: SHARED_STYLE_COLORS.backgroundSecondary,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    opacity: 0.6,
    gap: 8,
  },
  uploadDisabledText: {
    color: SHARED_STYLE_COLORS.textMuted,
    fontSize: 16,
    fontWeight: '600',
  },
  uploadDisabledSubtext: {
    color: SHARED_STYLE_COLORS.textMuted,
    fontSize: 14,
    textAlign: 'center',
  },
  form: {
    gap: 12,
  },
  formTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: SHARED_STYLE_COLORS.text,
    marginBottom: 12,
  },
  input: {
    backgroundColor: SHARED_STYLE_COLORS.backgroundSecondary,
    borderRadius: 12,
    padding: 16,
    color: SHARED_STYLE_COLORS.text,
    fontSize: 16,
  },
  textArea: {
    backgroundColor: SHARED_STYLE_COLORS.backgroundSecondary,
    borderRadius: 12,
    padding: 16,
    color: SHARED_STYLE_COLORS.text,
    fontSize: 16,
    textAlignVertical: 'top',
    minHeight: 100,
  },
  button: {
    backgroundColor: SHARED_STYLE_COLORS.primary,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    borderRadius: 12,
    gap: 8,
    minWidth: 120,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonText: {
    color: SHARED_STYLE_COLORS.text,
    fontSize: 16,
    fontWeight: '600',
  },
  formActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  skipButton: {
    padding: 12,
  },
  skipButtonText: {
    color: SHARED_STYLE_COLORS.textMuted,
    fontSize: 14,
  },
  videosList: {
    marginTop: 32,
    gap: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: SHARED_STYLE_COLORS.text,
    marginBottom: 12,
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyText: {
    color: SHARED_STYLE_COLORS.text,
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 12,
  },
  emptySubtext: {
    color: SHARED_STYLE_COLORS.textMuted,
    fontSize: 14,
  },
  metadataEditorContainer: {
    backgroundColor: SHARED_STYLE_COLORS.backgroundSecondary,
    borderRadius: 12,
    padding: 16,
    gap: 16,
  },
  metadataTitle: {
    color: SHARED_STYLE_COLORS.text,
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
  },
  metadataInputContainer: {
    gap: 8,
  },
  metadataInputLabel: {
    color: SHARED_STYLE_COLORS.text,
    fontSize: 14,
    fontWeight: '500',
  },
  metadataInput: {
    backgroundColor: SHARED_STYLE_COLORS.backgroundTertiary,
    borderRadius: 8,
    padding: 12,
    color: SHARED_STYLE_COLORS.text,
    fontSize: 16,
    borderWidth: 1,
    borderColor: SHARED_STYLE_COLORS.backgroundTertiary,
  },
  metadataTextArea: {
    backgroundColor: SHARED_STYLE_COLORS.backgroundTertiary,
    borderRadius: 8,
    padding: 12,
    color: SHARED_STYLE_COLORS.text,
    fontSize: 16,
    minHeight: 100,
    textAlignVertical: 'top',
    borderWidth: 1,
    borderColor: SHARED_STYLE_COLORS.backgroundTertiary,
  },
  metadataActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
    marginTop: 16,
  },
  cancelButton: {
    backgroundColor: SHARED_STYLE_COLORS.backgroundTertiary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  cancelButtonText: {
    color: SHARED_STYLE_COLORS.text,
    fontSize: 14,
    fontWeight: '500',
  },
  saveButton: {
    backgroundColor: SHARED_STYLE_COLORS.primary,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  saveButtonText: {
    color: SHARED_STYLE_COLORS.text,
    fontSize: 14,
    fontWeight: '600',
  },
  inputError: {
    borderColor: SHARED_STYLE_COLORS.error,
  },
  helperText: {
    color: SHARED_STYLE_COLORS.textMuted,
    fontSize: 12,
    marginTop: 4,
  },
  analysisActions: {
    marginBottom: 16,
  },
  rejectButton: {
    backgroundColor: SHARED_STYLE_COLORS.error,
    padding: 12,
    borderRadius: 8,
  },
  rejectButtonText: {
    color: SHARED_STYLE_COLORS.text,
    fontSize: 14,
    fontWeight: '600',
  },
  analysisHelperText: {
    color: SHARED_STYLE_COLORS.textMuted,
    fontSize: 12,
  },
});