export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          stripe_customer_id: string | null
          role: 'user' | 'admin'
          created_at: string
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          stripe_customer_id?: string | null
          role?: 'user' | 'admin'
          created_at?: string
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          stripe_customer_id?: string | null
          role?: 'user' | 'admin'
          created_at?: string
        }
      }
      editorial_profiles: {
        Row: {
          id: string
          user_id: string
          persona_description: string | null
          tone_of_voice: string | null
          audience: string | null
          content_examples: Json | null
          style_notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          persona_description?: string | null
          tone_of_voice?: string | null
          audience?: string | null
          content_examples?: Json | null
          style_notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          persona_description?: string | null
          tone_of_voice?: string | null
          audience?: string | null
          content_examples?: Json | null
          style_notes?: string | null
          created_at?: string
        }
      }
      // ... Additional table types will be generated by Supabase CLI
    }
  }
}