export const VIDEO_PRESETS = [
  {
    name: 'Karaoke',
    id: 'karaoke',
    font_family: 'Montserrat',
    font_weight: '700',
    font_size: '8 vmin',
    fill_color: '#ffffff',
    stroke_color: '#333333',
    stroke_width: '1.05 vmin',
    background_color: 'rgba(216,216,216,0)',
    background_x_padding: '26%',
    background_y_padding: '7%',
    background_border_radius: '28%',
    transcript_effect: 'karaoke',
    transcript_placement: 'animate',
    transcript_color: '#04f827',
    transcript_maximum_length: 25,
    width: '90%',
    height: '100%',
    placement: 'bottom',
  },
  {
    name: 'Beasty',
    id: 'beasty',
    font_family: 'Montserrat',
    font_weight: '700',
    font_size: '8 vmin',
    fill_color: '#ffffff',
    stroke_color: '#333333',
    stroke_width: '1.05 vmin',
    background_color: 'rgba(216,216,216,0)',
    background_x_padding: '26%',
    background_y_padding: '7%',
    background_border_radius: '28%',
    transcript_effect: 'highlight',
    transcript_placement: 'animate',
    transcript_color: '#FFFD03',
    transcript_maximum_length: 25,
    width: '90%',
    height: '100%',
    placement: 'bottom',
  },
  {
    name: 'Fade',
    id: 'fade',
    font_family: 'Montserrat',
    font_weight: '700',
    font_size: '8 vmin',
    fill_color: '#ffffff',
    stroke_color: '#333333',
    stroke_width: '1.05 vmin',
    background_color: 'rgba(216,216,216,0)',
    background_x_padding: '26%',
    background_y_padding: '7%',
    background_border_radius: '28%',
    transcript_effect: 'fade',
    transcript_placement: 'animate',
    transcript_color: '#ffffff',
    transcript_maximum_length: 25,
    width: '90%',
    height: '100%',
    placement: 'bottom',
  },
  {
    name: 'Bounce',
    id: 'bounce',
    font_family: 'Montserrat',
    font_weight: '700',
    font_size: '8 vmin',
    fill_color: '#ffffff',
    stroke_color: '#333333',
    stroke_width: '1.05 vmin',
    background_color: 'rgba(216,216,216,0)',
    background_x_padding: '26%',
    background_y_padding: '7%',
    background_border_radius: '28%',
    transcript_effect: 'bounce',
    transcript_placement: 'animate',
    transcript_color: '#ff4081',
    transcript_maximum_length: 25,
    width: '90%',
    height: '100%',
    placement: 'bottom',
  },
  {
    name: 'Slide',
    id: 'slide',
    font_family: 'Montserrat',
    font_weight: '700',
    font_size: '8 vmin',
    fill_color: '#ffffff',
    stroke_color: '#333333',
    stroke_width: '1.05 vmin',
    background_color: 'rgba(216,216,216,0)',
    background_x_padding: '26%',
    background_y_padding: '7%',
    background_border_radius: '28%',
    transcript_effect: 'slide',
    transcript_placement: 'animate',
    transcript_color: '#00bcd4',
    transcript_maximum_length: 25,
    width: '90%',
    height: '100%',
    placement: 'bottom',
  },
  {
    name: 'Enlarge',
    id: 'enlarge',
    font_family: 'Montserrat',
    font_weight: '700',
    font_size: '8 vmin',
    fill_color: '#ffffff',
    stroke_color: '#333333',
    stroke_width: '1.05 vmin',
    background_color: 'rgba(216,216,216,0)',
    background_x_padding: '26%',
    background_y_padding: '7%',
    background_border_radius: '28%',
    transcript_effect: 'enlarge',
    transcript_placement: 'animate',
    transcript_color: '#9c27b0',
    transcript_maximum_length: 25,
    width: '90%',
    height: '100%',
    placement: 'bottom',
  },
];
