export const VIDEO_PRESETS = [
  {
    name: 'Karaoke',
    id: 'karaoke',
    fontFamily: 'Montserrat',
    fontSize: 40,
    fontWeight: 'bold',
    fontColor: '#FFFFFF',
    uppercase: true,
    strokeColor: '#000000',
    strokeWidth: 8,
    shadow: true,
    shadowColor: '#000000',
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    shadowBlur: 2,
    animation: 'bounce',
    effect: 'karaoke',
    placement: 'bottom',
    highlightColor: '#04f827',
    maxWordsPerLine: 14,
  },
  {
    name: 'Beasty',
    id: 'beasty',
    fontFamily: 'Montserrat',
    fontSize: 40,
    fontWeight: 'bold',
    fontColor: '#FFFFFF',
    uppercase: true,
    strokeColor: '#000000',
    strokeWidth: 8,
    shadow: true,
    shadowColor: '#000000',
    shadowOffsetX: 2,
    shadowOffsetY: 2,
    shadowBlur: 2,
    animation: 'static',
    effect: 'highlight',
    placement: 'bottom',
    highlightColor: '#FFFD03',
    maxWordsPerLine: 14,
  },
];
